"""initial schema

Revision ID: 72af10f9a2b8
Revises: 
Create Date: 2026-04-24 15:53:01.688700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72af10f9a2b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSING', 'ANALYZED', 'ACTIONED', 'FAILED', 'PENDING_REVIEW', name='reportstatus'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('perception_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('action_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_created_at', 'reports', ['created_at'], unique=False)
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False)
    op.create_table('dead_letter_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifecycle_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('RECEIVED', 'PROCESSING', 'ANALYZED', 'ACTIONED', 'FAILED', 'PENDING_REVIEW', name='reportstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('RECEIVED', 'PROCESSING', 'ANALYZED', 'ACTIONED', 'FAILED', 'PENDING_REVIEW', name='reportstatus'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lifecycle_report_id', 'lifecycle_events', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lifecycle_report_id', table_name='lifecycle_events')
    op.drop_table('lifecycle_events')
    op.drop_table('dead_letter_queue')
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index('ix_reports_created_at', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
